-- ==============================================================================
-- DAILY CYBERSECURITY QUIZ APPLICATION - SUPABASE SETUP SCRIPT
-- ==============================================================================
-- Execute these SQL statements in your Supabase Project -> SQL Editor
-- Dashboard: https://supabase.com/dashboard/project/fzyozyaajamaesxycjzm/sql/new
-- ==============================================================================

-- 1. CREATE QUESTIONS TABLE
CREATE TABLE IF NOT EXISTS public.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "questionText" TEXT NOT NULL,
    "optionA" TEXT NOT NULL,
    "optionB" TEXT NOT NULL,
    "optionC" TEXT NOT NULL,
    "optionD" TEXT NOT NULL,
    "correctOption" VARCHAR(5) NOT NULL, -- 'A', 'B', 'C', or 'D'
    category VARCHAR(100) DEFAULT 'General Security',
    difficulty VARCHAR(50) DEFAULT 'Medium', -- 'Easy', 'Medium', 'Hard'
    active BOOLEAN DEFAULT true,
    "createdAt" TIMESTAMPTZ DEFAULT NOW(),
    "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CREATE USER ATTEMPTS TABLE
-- Privacy Mandate: ONLY stores userName, quizDate, isCorrect, score, bonusPoints, totalPoints, responseTimeMs, createdAt
-- DOES NOT store which question was answered or the user's selected option!
CREATE TABLE IF NOT EXISTS public.user_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userName" TEXT NOT NULL,
    "quizDate" VARCHAR(10) NOT NULL, -- Format: YYYY-MM-DD
    "isCorrect" BOOLEAN NOT NULL,
    score INT NOT NULL, -- Base score: 1 if correct, 0 if wrong
    "bonusPoints" INT NOT NULL, -- Speed bonus: 10, 8, 6, 4, 2, 1, 0
    "totalPoints" INT NOT NULL, -- score + bonusPoints
    "responseTimeMs" INT NOT NULL, -- Milliseconds taken to answer
    category TEXT DEFAULT 'General Security',
    "createdAt" TIMESTAMPTZ DEFAULT NOW()
);

-- Migration query if table already exists in Supabase
ALTER TABLE public.user_attempts ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'General Security';


-- 3. INDEXES FOR HIGH PERFORMANCE
CREATE INDEX IF NOT EXISTS idx_questions_active ON public.questions(active);
CREATE INDEX IF NOT EXISTS idx_user_attempts_username ON public.user_attempts("userName");
CREATE INDEX IF NOT EXISTS idx_user_attempts_quizdate ON public.user_attempts("quizDate");
CREATE INDEX IF NOT EXISTS idx_user_attempts_username_quizdate ON public.user_attempts("userName", "quizDate");
CREATE INDEX IF NOT EXISTS idx_user_attempts_total_points ON public.user_attempts("totalPoints" DESC, "responseTimeMs" ASC);

-- 4. ROW LEVEL SECURITY (RLS) POLICIES
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_attempts ENABLE ROW LEVEL SECURITY;

-- Full CRUD Policy for Questions (Select, Insert, Update, Delete)
DROP POLICY IF EXISTS "Enable all access for questions" ON public.questions;
DROP POLICY IF EXISTS "Public can read active questions" ON public.questions;
CREATE POLICY "Enable all access for questions" 
ON public.questions FOR ALL 
TO anon, authenticated 
USING (true) 
WITH CHECK (true);

-- Full Access Policy for User Attempts
DROP POLICY IF EXISTS "Enable all access for user_attempts" ON public.user_attempts;
DROP POLICY IF EXISTS "Public can read user attempts" ON public.user_attempts;
DROP POLICY IF EXISTS "Public can submit quiz attempt" ON public.user_attempts;
CREATE POLICY "Enable all access for user_attempts" 
ON public.user_attempts FOR ALL 
TO anon, authenticated 
USING (true) 
WITH CHECK (true);

-- 5. VERBATIM RANDOM QUESTION SELECTION QUERY (POSTGRES / SUPABASE)
-- SELECT id, "questionText", "optionA", "optionB", "optionC", "optionD", category, difficulty
-- FROM public.questions
-- WHERE active = true
-- ORDER BY RANDOM()
-- LIMIT 1;

-- 6. SEED QUESTION BANK WITH CYBERSECURITY QUESTIONS
INSERT INTO public.questions ("questionText", "optionA", "optionB", "optionC", "optionD", "correctOption", category, difficulty, active) VALUES
('Which social engineering attack tricks victims into clicking malicious links via SMS text messages?', 'Phishing', 'Smishing', 'Vishing', 'Spear Phishing', 'B', 'Social Engineering', 'Easy', true),
('What type of encryption uses a pair of public and private keys for secure communication?', 'Symmetric Encryption', 'Asymmetric Encryption', 'Hashing', 'Steganography', 'B', 'Cryptography', 'Medium', true),
('Which security framework principles dictate "Never Trust, Always Verify"?', 'Defense in Depth', 'Principle of Least Privilege', 'Zero Trust Architecture', 'Role-Based Access Control', 'C', 'Security Architecture', 'Easy', true),
('What is the primary function of a Web Application Firewall (WAF)?', 'Encrypt hard drive partitions', 'Filter, monitor, and block HTTP traffic to/from a web application', 'Generate strong user passwords automatically', 'Prevent hardware theft in data centers', 'B', 'Network Security', 'Medium', true),
('Which vulnerability type occurs when untrusted user input is directly rendered into an HTML document without sanitization?', 'SQL Injection', 'Cross-Site Scripting (XSS)', 'Cross-Site Request Forgery (CSRF)', 'Buffer Overflow', 'B', 'Web Security', 'Hard', true),
('Which port is standard for secure HTTPS web traffic?', 'Port 80', 'Port 22', 'Port 443', 'Port 8080', 'C', 'Network Security', 'Easy', true),
('What malware type encrypts victim files and demands payment for the decryption key?', 'Spyware', 'Adware', 'Ransomware', 'Trojan', 'C', 'Malware', 'Easy', true),
('What does the abbreviation "SIEM" stand for in cybersecurity operations?', 'System Information and Emergency Monitoring', 'Security Information and Event Management', 'Secure Infrastructure & Endpoint Maintenance', 'Server Inspection and Encryption Module', 'B', 'Security Operations', 'Medium', true),
('Which hashing algorithm is widely considered cryptographically broken and vulnerable to collision attacks?', 'SHA-256', 'MD5', 'SHA-512', 'BLAKE2', 'B', 'Cryptography', 'Medium', true),
('What is the technique called when an attacker spoofs an IP address to flood a target system with requests?', 'Man-in-the-Middle Attack', 'Denial of Service (DoS) / SYN Flood', 'DNS Poisoning', 'Pass-the-Hash', 'B', 'Network Attacks', 'Medium', true),
('Which HTTP security header forces browsers to use HTTPS only for future requests?', 'Content-Security-Policy', 'X-Frame-Options', 'HTTP Strict Transport Security (HSTS)', 'Access-Control-Allow-Origin', 'C', 'Web Security', 'Hard', true),
('What is Multi-Factor Authentication (MFA) designed to prevent?', 'DDoS attacks on servers', 'Unauthorized access due to stolen or compromised passwords', 'SQL injection in database forms', 'Wi-Fi eavesdropping', 'B', 'Identity & Access Management', 'Easy', true),
('Which attack manipulates DNS servers to redirect legitimate website traffic to a fake malicious site?', 'DNS Spoofing / Poisoning', 'BGP Hijacking', 'ARP Spoofing', 'Session Hijacking', 'A', 'Network Security', 'Medium', true),
('What is a "Zero-Day" vulnerability?', 'A bug that takes zero days to patch', 'A security vulnerability unknown to the vendor, with 0 days of protection available', 'A malware strain that destroys hardware on day zero', 'A password policy requiring daily expiration', 'B', 'Threat Intelligence', 'Easy', true),
('What is the main defense against SQL Injection vulnerabilities in server applications?', 'Client-side JavaScript validation only', 'Using Parameterized Queries / Prepared Statements', 'Increasing database connection timeout', 'Storing passwords in plain text', 'B', 'Secure Coding', 'Medium', true),
('Which tool is commonly used by cybersecurity teams for network packet analysis?', 'Wireshark', 'Burp Suite', 'Metasploit', 'John the Ripper', 'A', 'Security Tools', 'Easy', true),
('What type of attack involves an adversary secretly relaying and possibly altering communication between two parties who believe they are directly communicating?', 'Replay Attack', 'Man-in-the-Middle (MitM) Attack', 'Brute Force Attack', 'Dictionary Attack', 'B', 'Network Security', 'Medium', true),
('What is the practice of restricting user privileges to only what is strictly necessary to perform their job duties?', 'Separation of Duties', 'Principle of Least Privilege (PoLP)', 'Need to Know', 'Mandatory Access Control', 'B', 'IAM & Governance', 'Easy', true),
('What is the key difference between a Computer Virus and a Computer Worm?', 'Viruses affect PCs while Worms affect Macs', 'A virus requires a host file to execute, whereas a worm self-replicates independently over networks', 'Worms only infect emails', 'Viruses are legal security tools', 'B', 'Malware', 'Medium', true),
('Which cybersecurity standard specifically regulates the handling of credit card and payment data?', 'HIPAA', 'GDPR', 'PCI-DSS', 'SOX', 'C', 'Compliance & Standards', 'Easy', true);

-- ==============================================================================
-- 7. CREATE USER PROFILES TABLE
-- Stores full name, nickname, email ID, and email type (college vs personal)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "fullName" TEXT NOT NULL,
    "nickname" TEXT NOT NULL UNIQUE,
    "isNicknameSame" BOOLEAN DEFAULT false,
    "email" TEXT NOT NULL,
    "emailType" VARCHAR(20) DEFAULT 'college', -- 'college' or 'personal'
    "createdAt" TIMESTAMPTZ DEFAULT NOW(),
    "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast user profile lookups
CREATE INDEX IF NOT EXISTS idx_user_profiles_nickname ON public.user_profiles("nickname");
CREATE INDEX IF NOT EXISTS idx_user_profiles_email ON public.user_profiles("email");

-- Enable Row Level Security (RLS)
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

-- ==============================================================================
-- 8. CREATE ADMIN USERS TABLE
-- Stores email, password hash, name, active status for authorized quiz admins
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" TEXT NOT NULL UNIQUE,
    "passwordHash" TEXT NOT NULL,
    "name" TEXT,
    "active" BOOLEAN DEFAULT true,
    "createdAt" TIMESTAMPTZ DEFAULT NOW(),
    "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast admin user lookups by email
CREATE INDEX IF NOT EXISTS idx_admin_users_email ON public.admin_users("email");

-- Enable Row Level Security (RLS)
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- RLS Policy for Admin Users
DROP POLICY IF EXISTS "Enable all access for admin_users" ON public.admin_users;
CREATE POLICY "Enable all access for admin_users" 
ON public.admin_users FOR ALL 
TO anon, authenticated 
USING (true) 
WITH CHECK (true);

