const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const sampleQuestions = [
  {
    scenario: 'Rahul works as a system administrator and needs to set a master password for a secure server. He wants to pick the option that provides the highest possible resistance against modern cracking tools.',
    questionText: 'Which of the following employee passwords meets this requirement?',
    optionA: 'Password123!',
    optionB: 'Admin@2026',
    optionC: 'correct-horse-battery-staple-9#Z',
    optionD: 'P@$$w0rd',
    correctOption: 'C',
    category: 'Password Security',
    difficulty: 'Medium',
    active: true,
  },
  {
    scenario: 'An employee in the finance department receives an urgent email claiming to be from the CEO asking to immediately wire $50,000 to an overseas supplier before the end of the day. The sender address is spoofed to look like ceo@company-corp.com.',
    questionText: 'What specific type of targeted social engineering attack is taking place here?',
    optionA: 'Watering Hole Attack',
    optionB: 'Business Email Compromise (BEC) / Spear Phishing',
    optionC: 'DNS Cache Poisoning',
    optionD: 'Cross-Site Scripting (XSS)',
    correctOption: 'B',
    category: 'Social Engineering',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'Which social engineering attack tricks victims into clicking malicious links via SMS text messages?',
    optionA: 'Phishing',
    optionB: 'Smishing',
    optionC: 'Vishing',
    optionD: 'Spear Phishing',
    correctOption: 'B',
    category: 'Social Engineering',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'What type of encryption uses a pair of public and private keys for secure communication?',
    optionA: 'Symmetric Encryption',
    optionB: 'Asymmetric Encryption',
    optionC: 'Hashing',
    optionD: 'Steganography',
    correctOption: 'B',
    category: 'Cryptography',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'Which security framework principles dictate "Never Trust, Always Verify"?',
    optionA: 'Defense in Depth',
    optionB: 'Principle of Least Privilege',
    optionC: 'Zero Trust Architecture',
    optionD: 'Role-Based Access Control',
    correctOption: 'C',
    category: 'Security Architecture',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'What is the primary function of a Web Application Firewall (WAF)?',
    optionA: 'Encrypt hard drive partitions',
    optionB: 'Filter, monitor, and block HTTP traffic to/from a web application',
    optionC: 'Generate strong user passwords automatically',
    optionD: 'Prevent hardware theft in data centers',
    correctOption: 'B',
    category: 'Network Security',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'Which vulnerability type occurs when untrusted user input is directly rendered into an HTML document without sanitization?',
    optionA: 'SQL Injection',
    optionB: 'Cross-Site Scripting (XSS)',
    optionC: 'Cross-Site Request Forgery (CSRF)',
    optionD: 'Buffer Overflow',
    correctOption: 'B',
    category: 'Web Security',
    difficulty: 'Hard',
    active: true,
  },
  {
    questionText: 'Which port is standard for secure HTTPS web traffic?',
    optionA: 'Port 80',
    optionB: 'Port 22',
    optionC: 'Port 443',
    optionD: 'Port 8080',
    correctOption: 'C',
    category: 'Network Security',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'What malware type encrypts victim files and demands payment for the decryption key?',
    optionA: 'Spyware',
    optionB: 'Adware',
    optionC: 'Ransomware',
    optionD: 'Trojan',
    correctOption: 'C',
    category: 'Malware',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'What does the abbreviation "SIEM" stand for in cybersecurity operations?',
    optionA: 'System Information and Emergency Monitoring',
    optionB: 'Security Information and Event Management',
    optionC: 'Secure Infrastructure & Endpoint Maintenance',
    optionD: 'Server Inspection and Encryption Module',
    correctOption: 'B',
    category: 'Security Operations',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'Which hashing algorithm is widely considered cryptographically broken and vulnerable to collision attacks?',
    optionA: 'SHA-256',
    optionB: 'MD5',
    optionC: 'SHA-512',
    optionD: 'BLAKE2',
    correctOption: 'B',
    category: 'Cryptography',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'What is the technique called when an attacker spoofs an IP address to flood a target system with requests?',
    optionA: 'Man-in-the-Middle Attack',
    optionB: 'Denial of Service (DoS) / SYN Flood',
    optionC: 'DNS Poisoning',
    optionD: 'Pass-the-Hash',
    correctOption: 'B',
    category: 'Network Attacks',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'Which HTTP security header forces browsers to use HTTPS only for future requests?',
    optionA: 'Content-Security-Policy',
    optionB: 'X-Frame-Options',
    optionC: 'HTTP Strict Transport Security (HSTS)',
    optionD: 'Access-Control-Allow-Origin',
    correctOption: 'C',
    category: 'Web Security',
    difficulty: 'Hard',
    active: true,
  },
  {
    questionText: 'What is Multi-Factor Authentication (MFA) designed to prevent?',
    optionA: 'DDoS attacks on servers',
    optionB: 'Unauthorized access due to stolen or compromised passwords',
    optionC: 'SQL injection in database forms',
    optionD: 'Wi-Fi eavesdropping',
    correctOption: 'B',
    category: 'Identity & Access Management',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'Which attack manipulates DNS servers to redirect legitimate website traffic to a fake malicious site?',
    optionA: 'DNS Spoofing / Poisoning',
    optionB: 'BGP Hijacking',
    optionC: 'ARP Spoofing',
    optionD: 'Session Hijacking',
    correctOption: 'A',
    category: 'Network Security',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'What is a "Zero-Day" vulnerability?',
    optionA: 'A bug that takes zero days to patch',
    optionB: 'A security vulnerability unknown to the vendor, with 0 days of protection available',
    optionC: 'A malware strain that destroys hardware on day zero',
    optionD: 'A password policy requiring daily expiration',
    correctOption: 'B',
    category: 'Threat Intelligence',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'What is the main defense against SQL Injection vulnerabilities in server applications?',
    optionA: 'Client-side JavaScript validation only',
    optionB: 'Using Parameterized Queries / Prepared Statements',
    optionC: 'Increasing database connection timeout',
    optionD: 'Storing passwords in plain text',
    correctOption: 'B',
    category: 'Secure Coding',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'Which tool is commonly used by cybersecurity teams for network packet analysis?',
    optionA: 'Wireshark',
    optionB: 'Burp Suite',
    optionC: 'Metasploit',
    optionD: 'John the Ripper',
    correctOption: 'A',
    category: 'Security Tools',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'What type of attack involves an adversary secretly relaying and possibly altering communication between two parties who believe they are directly communicating?',
    optionA: 'Replay Attack',
    optionB: 'Man-in-the-Middle (MitM) Attack',
    optionC: 'Brute Force Attack',
    optionD: 'Dictionary Attack',
    correctOption: 'B',
    category: 'Network Security',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'What is the practice of restricting user privileges to only what is strictly necessary to perform their job duties?',
    optionA: 'Separation of Duties',
    optionB: 'Principle of Least Privilege (PoLP)',
    optionC: 'Need to Know',
    optionD: 'Mandatory Access Control',
    correctOption: 'B',
    category: 'IAM & Governance',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'What is the key difference between a Computer Virus and a Computer Worm?',
    optionA: 'Viruses affect PCs while Worms affect Macs',
    optionB: 'A virus requires a host file to execute, whereas a worm self-replicates independently over networks',
    optionC: 'Worms only infect emails',
    optionD: 'Viruses are legal security tools',
    correctOption: 'B',
    category: 'Malware',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'Which cybersecurity standard specifically regulates the handling of credit card and payment data?',
    optionA: 'HIPAA',
    optionB: 'GDPR',
    optionC: 'PCI-DSS',
    optionD: 'SOX',
    correctOption: 'C',
    category: 'Compliance & Standards',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'What is the primary security goal of the OAuth 2.0 protocol?',
    optionA: 'User authentication',
    optionB: 'API authorization',
    optionC: 'Data encryption at rest',
    optionD: 'Network traffic routing',
    correctOption: 'B',
    category: 'Identity & Access Management',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'Which attack vector targets the DNS system by flooding the cache with false IP mappings?',
    optionA: 'DNS Spoofing / Poisoning',
    optionB: 'SYN Flood',
    optionC: 'DDoS Reflection',
    optionD: 'ARP Poisoning',
    correctOption: 'A',
    category: 'Network Attacks',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'In AWS, what does the Shared Responsibility Model state regarding cloud security?',
    optionA: 'AWS is responsible for security IN the cloud',
    optionB: 'The customer is responsible for security OF the cloud',
    optionC: 'AWS is responsible for security OF the cloud, and the customer is responsible for security IN the cloud',
    optionD: 'AWS assumes 100% of all security liability',
    correctOption: 'C',
    category: 'Cloud Security',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'What type of firewall filters traffic based on the application layer, understanding protocol-specific commands?',
    optionA: 'Packet Filter',
    optionB: 'Stateful Inspection Firewall',
    optionC: 'Next-Generation Firewall (NGFW) / Application Firewall',
    optionD: 'Circuit-Level Gateway',
    correctOption: 'C',
    category: 'Network Security',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'Which hashing algorithm is widely used to verify the integrity of downloaded files and is 256 bits long?',
    optionA: 'MD5',
    optionB: 'SHA-1',
    optionC: 'SHA-256',
    optionD: 'bcrypt',
    correctOption: 'C',
    category: 'Cryptography',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'What is a "Man-in-the-Middle" (MitM) attack?',
    optionA: 'An attacker physical stealing a backup drive',
    optionB: 'An attacker intercepts and possibly alters communication between two targets',
    optionC: 'An employee sharing their passwords with colleagues',
    optionD: 'A program that self-replicates through emails',
    correctOption: 'B',
    category: 'Network Security',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'Which term refers to the process of converting ciphertext back into plaintext?',
    optionA: 'Encryption',
    optionB: 'Hashing',
    optionC: 'Decryption',
    optionD: 'Obfuscation',
    correctOption: 'C',
    category: 'Cryptography',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'What does a "Cold Site" describe in business continuity and disaster recovery?',
    optionA: 'A location with power, heating, cooling, and all server equipment ready to run immediately',
    optionB: 'A backup facility with electrical connections and physical space, but no server hardware pre-installed',
    optionC: 'A data center in a cold geographical region to save on cooling costs',
    optionD: 'A backup tape storage unit kept in a refrigerator',
    correctOption: 'B',
    category: 'Disaster Recovery',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'Which port is standard for SSH (Secure Shell) traffic?',
    optionA: 'Port 21',
    optionB: 'Port 22',
    optionC: 'Port 23',
    optionD: 'Port 80',
    correctOption: 'B',
    category: 'Network Security',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'What is the primary purpose of a Honeypot in a network environment?',
    optionA: 'To speed up web cache delivery',
    optionB: 'To lure and detect attackers, study their tactics, and distract them from real assets',
    optionC: 'To block SQL injection requests',
    optionD: 'To manage employee password resets',
    correctOption: 'B',
    category: 'Security Operations',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'Which component of the CIA Triad is compromised when unauthorized modifications are made to a database?',
    optionA: 'Confidentiality',
    optionB: 'Integrity',
    optionC: 'Availability',
    optionD: 'Non-repudiation',
    correctOption: 'B',
    category: 'General Security',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'What is the main objective of a "Whaling" phishing attack?',
    optionA: 'Targeting a large number of random email users at once',
    optionB: 'Targeting high-profile executives or individuals with high authority',
    optionC: 'Compromising industrial control systems in maritime operations',
    optionD: 'Hijacking domain name registrars',
    correctOption: 'B',
    category: 'Social Engineering',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'Which security control is designed to limit the damage from a successful attack by dividing a network into smaller zones?',
    optionA: 'Network Segmentation',
    optionB: 'Load Balancing',
    optionC: 'Single Sign-On (SSO)',
    optionD: 'Intrusion Detection System (IDS)',
    correctOption: 'A',
    category: 'Network Security',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'What does the term "Salting" refer to in password security?',
    optionA: 'Encrypting the password database with a master key',
    optionB: 'Adding random data to a password before hashing it to prevent dictionary/rainbow table attacks',
    optionC: 'Limiting password length to 8 characters',
    optionD: 'Periodically forcing users to change their password',
    correctOption: 'B',
    category: 'Cryptography',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'Which type of attack exploits the trust a site has in a user\'s browser by sending unauthorized commands from a logged-in user?',
    optionA: 'Cross-Site Scripting (XSS)',
    optionB: 'Cross-Site Request Forgery (CSRF)',
    optionC: 'SQL Injection',
    optionD: 'Directory Traversal',
    correctOption: 'B',
    category: 'Web Security',
    difficulty: 'Hard',
    active: true,
  },
  {
    questionText: 'What is the purpose of the Address Resolution Protocol (ARP)?',
    optionA: 'To resolve domain names to IP addresses',
    optionB: 'To resolve IP addresses to physical MAC addresses',
    optionC: 'To secure network traffic via encryption',
    optionD: 'To assign dynamic IP addresses to hosts',
    correctOption: 'B',
    category: 'Network Security',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'Which standard symmetric key encryption algorithm was adopted by the US government and is widely used worldwide today?',
    optionA: 'DES',
    optionB: '3DES',
    optionC: 'AES',
    optionD: 'Blowfish',
    correctOption: 'C',
    category: 'Cryptography',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'What is a Rootkit?',
    optionA: 'Malware designed to gain administrative control over a system while actively hiding its presence',
    optionB: 'An automated tool to configure database tables',
    optionC: 'A standard backup utility built into Unix systems',
    optionD: 'A script to optimize computer startup time',
    correctOption: 'A',
    category: 'Malware',
    difficulty: 'Hard',
    active: true,
  },
  {
    questionText: 'What is "Data Loss Prevention" (DLP) software designed to do?',
    optionA: 'Prevent hard drives from failing physically',
    optionB: 'Detect and prevent unauthorized transmission or leakage of sensitive data outside the corporate network',
    optionC: 'Compress files to save server storage space',
    optionD: 'Restore deleted files from automated cloud backups',
    correctOption: 'B',
    category: 'Data Security',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'Which framework is an open-source security standard for authorization that allows third-party applications to access resources on behalf of a user?',
    optionA: 'SAML 2.0',
    optionB: 'OpenID Connect',
    optionC: 'OAuth 2.0',
    optionD: 'LDAP',
    correctOption: 'C',
    category: 'Identity & Access Management',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'What is the primary function of the "Transport Layer Security" (TLS) protocol?',
    optionA: 'To check files for malware before they are downloaded',
    optionB: 'To secure and encrypt communications over computer networks',
    optionC: 'To assign IP addresses to new network devices',
    optionD: 'To block incoming port scans from unauthorized IP ranges',
    correctOption: 'B',
    category: 'Cryptography',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'Which term describes a vulnerability where an application fails to check authorization before accessing a specific object or record by its ID?',
    optionA: 'SQL Injection',
    optionB: 'Insecure Direct Object Reference (IDOR)',
    optionC: 'Buffer Overflow',
    optionD: 'Cross-Site Scripting',
    correctOption: 'B',
    category: 'Web Security',
    difficulty: 'Hard',
    active: true,
  },
  {
    questionText: 'What type of access control model restricts access based on the security clearance of users and classification level of resources?',
    optionA: 'Discretionary Access Control (DAC)',
    optionB: 'Mandatory Access Control (MAC)',
    optionC: 'Role-Based Access Control (RBAC)',
    optionD: 'Rule-Based Access Control',
    correctOption: 'B',
    category: 'Identity & Access Management',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'Which attack involves sending fragmented packets to a target system that cannot reassemble them, causing it to crash?',
    optionA: 'Smurf Attack',
    optionB: 'Ping of Death',
    optionC: 'Teardrop Attack',
    optionD: 'Slowloris',
    correctOption: 'C',
    category: 'Network Attacks',
    difficulty: 'Hard',
    active: true,
  },
  {
    questionText: 'What does a "Kerberos" protocol secure?',
    optionA: 'Wireless router connections using WPA3',
    optionB: 'Network authentication using ticket-granting tickets to prove identity over insecure channels',
    optionC: 'Cloud storage backup snapshots',
    optionD: 'Database table transaction logs',
    correctOption: 'B',
    category: 'Identity & Access Management',
    difficulty: 'Hard',
    active: true,
  },
  {
    questionText: 'Which type of backup copies all files that have changed since the last full backup, without resetting the archive bit?',
    optionA: 'Incremental Backup',
    optionB: 'Differential Backup',
    optionC: 'Daily Backup',
    optionD: 'Snapshot Backup',
    correctOption: 'B',
    category: 'Disaster Recovery',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'What is the main purpose of "Certificate Authorities" (CAs) in public key cryptography?',
    optionA: 'To encrypt emails before sending them',
    optionB: 'To generate private keys for web application clients',
    optionC: 'To validate, sign, and issue digital certificates verifying the identity of entities',
    optionD: 'To block phishing domains automatically at the ISP level',
    correctOption: 'C',
    category: 'Cryptography',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'What is the security risk of using default SNMP community strings like "public" or "private"?',
    optionA: 'They use too much system memory',
    optionB: 'They allow unauthorized users to read or modify network device configuration metrics easily',
    optionC: 'They are incompatible with modern routing protocols',
    optionD: 'They cause local network printers to stop working',
    correctOption: 'B',
    category: 'Network Security',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'Which malware type replicates itself across networks without needing any human interaction or host file execution?',
    optionA: 'Trojan Horse',
    optionB: 'Virus',
    optionC: 'Worm',
    optionD: 'Spyware',
    correctOption: 'C',
    category: 'Malware',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'What does a "Buffer Overflow" vulnerability allow an attacker to do?',
    optionA: 'Exhaust all memory on a target database server',
    optionB: 'Overwrite executable memory to hijack program flow and potentially execute arbitrary code',
    optionC: 'Redirect DNS queries to a malicious web page',
    optionD: 'Eavesdrop on unencrypted Wi-Fi traffic',
    correctOption: 'B',
    category: 'Secure Coding',
    difficulty: 'Hard',
    active: true,
  },
  {
    questionText: 'Which regulatory standard mandates security measures for organizations handling European Union citizens\' personal data?',
    optionA: 'HIPAA',
    optionB: 'GDPR',
    optionC: 'SOX',
    optionD: 'PCI-DSS',
    correctOption: 'B',
    category: 'Compliance & Standards',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'What is a "Logic Bomb"?',
    optionA: 'Malware that deletes database records when a specific logical condition or time trigger is met',
    optionB: 'A mathematical algorithm to verify password strength',
    optionC: 'A high-speed firewall configuration module',
    optionD: 'An interactive quiz terminal software tool',
    correctOption: 'A',
    category: 'Malware',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'Which encryption method uses the same single secret key for both encrypting and decrypting data?',
    optionA: 'Asymmetric Encryption',
    optionB: 'Symmetric Encryption',
    optionC: 'Diffie-Hellman Key Exchange',
    optionD: 'Public Key Cryptography',
    correctOption: 'B',
    category: 'Cryptography',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'What is the role of an Identity Provider (IdP) in a Single Sign-On (SSO) architecture?',
    optionA: 'To encrypt database user passwords',
    optionB: 'To authenticate user identities and issue security assertions / tokens to Service Providers',
    optionC: 'To monitor local firewall connection logs',
    optionD: 'To generate temporary passwords for remote client machines',
    correctOption: 'B',
    category: 'Identity & Access Management',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'What type of social engineering attack involves an attacker sending targeted, personalized emails to a specific organization or individual?',
    optionA: 'Phishing',
    optionB: 'Vishing',
    optionC: 'Spear Phishing',
    optionD: 'Tailgating',
    correctOption: 'C',
    category: 'Social Engineering',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'Which network security concept establishes a secure private tunnel across a public network like the Internet?',
    optionA: 'Virtual Local Area Network (VLAN)',
    optionB: 'Virtual Private Network (VPN)',
    optionC: 'Domain Name System Security Extensions (DNSSEC)',
    optionD: 'Software-Defined Networking (SDN)',
    correctOption: 'B',
    category: 'Network Security',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'In incident response, what is the primary goal of the "Containment" phase?',
    optionA: 'To identify the root cause of the security breach',
    optionB: 'To limit the scope and magnitude of a security incident to prevent further damage',
    optionC: 'To restore affected systems back to normal operations',
    optionD: 'To write a post-incident report for stakeholders',
    correctOption: 'B',
    category: 'Incident Response',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'What is the primary risk associated with "Cross-Site Scripting" (XSS) vulnerabilities?',
    optionA: 'Unauthorized deletion of database records on the server',
    optionB: 'Execution of malicious JavaScript code in the context of the victim\'s browser session',
    optionC: 'Slowing down web page layout rendering times',
    optionD: 'Exhausting network bandwidth on target server hosts',
    correctOption: 'B',
    category: 'Web Security',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'Which physical security measure involves a double-door entry system designed to prevent tailgating?',
    optionA: 'Turnstile gate',
    optionB: 'Mantrap / Security Vestibule',
    optionC: 'Biometric Scanner',
    optionD: 'Smart card reader',
    correctOption: 'B',
    category: 'Physical Security',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'What does "Perfect Forward Secrecy" (PFS) guarantee in cryptographic protocols?',
    optionA: 'Encrypted files cannot be deleted by attackers',
    optionB: 'Compromise of a long-term private key does not compromise past session keys used for decryption',
    optionC: 'Passwords are encrypted with a random key length automatically',
    optionD: 'Symmetric keys are generated using quantum random number generators',
    correctOption: 'B',
    category: 'Cryptography',
    difficulty: 'Hard',
    active: true,
  },
  {
    questionText: 'Which protocol secures wireless networks by generating a unique encryption key for each packet using Simultaneous Authentication of Equals (SAE)?',
    optionA: 'WEP',
    optionB: 'WPA',
    optionC: 'WPA2',
    optionD: 'WPA3',
    correctOption: 'D',
    category: 'Network Security',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'What is the purpose of a "DKIM" (DomainKeys Identified Mail) DNS record?',
    optionA: 'To encrypt the bodies of all incoming emails',
    optionB: 'To provide a cryptographic signature to verify that an email was sent from an authorized domain owner',
    optionC: 'To block emails containing attachments larger than 10MB',
    optionD: 'To list authorized email senders for an organization',
    correctOption: 'B',
    category: 'Network Security',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'What type of security assessment involves mimicking the tactics, techniques, and procedures (TTPs) of real-world adversaries without prior warning to the defense team?',
    optionA: 'Vulnerability Assessment',
    optionB: 'Penetration Testing',
    optionC: 'Red Teaming',
    optionD: 'Static Code Analysis',
    correctOption: 'C',
    category: 'Security Operations',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'Which attack vector involves an attacker tricking a database into executing arbitrary commands by manipulating inputs on web forms?',
    optionA: 'Cross-Site Scripting (XSS)',
    optionB: 'SQL Injection (SQLi)',
    optionC: 'Insecure Direct Object Reference (IDOR)',
    optionD: 'Command Injection',
    correctOption: 'B',
    category: 'Web Security',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'Which security mechanism is designed to prevent a user from denying that they performed a specific action or transaction?',
    optionA: 'Confidentiality',
    optionB: 'Availability',
    optionC: 'Non-Repudiation',
    optionD: 'Authorization',
    correctOption: 'C',
    category: 'General Security',
    difficulty: 'Easy',
    active: true,
  },
  {
    questionText: 'What is the primary risk of using "Docker" containers with root privileges by default?',
    optionA: 'Container images consume too much storage space',
    optionB: 'An attacker exploiting a container escape vulnerability would immediately gain administrative host access',
    optionC: 'Containers take longer to startup',
    optionD: 'Container network ports cannot be exposed publicly',
    correctOption: 'B',
    category: 'Cloud Security',
    difficulty: 'Hard',
    active: true,
  },
  {
    questionText: 'Which DNS security feature prevents DNS spoofing by cryptographically signing DNS records?',
    optionA: 'DNSSEC',
    optionB: 'DoH (DNS over HTTPS)',
    optionC: 'DoT (DNS over TLS)',
    optionD: 'Dynamic DNS',
    correctOption: 'A',
    category: 'Network Security',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'What is the function of the "Access Token" in OAuth 2.0 authorization flows?',
    optionA: 'To verify the user\'s password credentials directly',
    optionB: 'To grant the client application access to specific APIs and user resources on the resource server',
    optionC: 'To encrypt all web traffic between client and server',
    optionD: 'To record audit logs of authentication attempts',
    correctOption: 'B',
    category: 'Identity & Access Management',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'Which phase of the Software Development Life Cycle (SDLC) is the most cost-effective stage to discover and resolve security bugs?',
    optionA: 'Design & Requirements',
    optionB: 'Testing & QA',
    optionC: 'Deployment / Production',
    optionD: 'Maintenance',
    correctOption: 'A',
    category: 'Secure Coding',
    difficulty: 'Medium',
    active: true,
  },
  {
    questionText: 'What is the name of the framework developed by MITRE to map and catalog adversarial tactics, techniques, and procedures (TTPs)?',
    optionA: 'NIST CSF',
    optionB: 'MITRE ATT&CK',
    optionC: 'OWASP Top 10',
    optionD: 'ISO 27001',
    correctOption: 'B',
    category: 'Threat Intelligence',
    difficulty: 'Easy',
    active: true,
  }
];

async function main() {
  console.log('Starting seed process...');
  await prisma.question.deleteMany();
  console.log('Cleared existing questions.');

  for (const q of sampleQuestions) {
    await prisma.question.create({
      data: q,
    });
  }

  console.log(`Successfully seeded ${sampleQuestions.length} cybersecurity questions into SQLite.`);
}

main()
  .catch((e) => {
    console.error('Error during seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
