const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const questions = [
  // === NETWORK SECURITY ===
  {
    questionText: "What does the acronym 'VPN' stand for?",
    optionA: "Virtual Private Network",
    optionB: "Virtual Public Node",
    optionC: "Verified Protocol Network",
    optionD: "Variable Packet Notation",
    correctOption: "A",
    category: "Network Security",
    difficulty: "Easy",
    active: true,
  },
  {
    questionText: "Which protocol is used to securely transfer files over a network?",
    optionA: "FTP",
    optionB: "SFTP",
    optionC: "SMTP",
    optionD: "SNMP",
    correctOption: "B",
    category: "Network Security",
    difficulty: "Easy",
    active: true,
  },
  {
    questionText: "What is a 'firewall' in network security?",
    optionA: "A device that speeds up internet connections",
    optionB: "A system that monitors and controls incoming and outgoing traffic",
    optionC: "A type of malware that encrypts files",
    optionD: "A tool used for password cracking",
    correctOption: "B",
    category: "Network Security",
    difficulty: "Easy",
    active: true,
  },
  {
    questionText: "Which OSI layer is responsible for end-to-end communication and error recovery?",
    optionA: "Network Layer",
    optionB: "Data Link Layer",
    optionC: "Transport Layer",
    optionD: "Session Layer",
    correctOption: "C",
    category: "Network Security",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What type of attack involves flooding a network with traffic to make a service unavailable?",
    optionA: "Man-in-the-Middle Attack",
    optionB: "SQL Injection",
    optionC: "Denial of Service (DoS) Attack",
    optionD: "Cross-Site Scripting",
    correctOption: "C",
    category: "Network Security",
    difficulty: "Easy",
    active: true,
  },
  {
    questionText: "What is 'ARP Spoofing' used to accomplish by attackers?",
    optionA: "Crack Wi-Fi passwords",
    optionB: "Intercept network traffic by linking the attacker's MAC to a legitimate IP",
    optionC: "Inject SQL commands into databases",
    optionD: "Encrypt data transmissions",
    correctOption: "B",
    category: "Network Security",
    difficulty: "Hard",
    active: true,
  },
  {
    questionText: "Which port does HTTPS traffic typically use?",
    optionA: "80",
    optionB: "21",
    optionC: "443",
    optionD: "25",
    correctOption: "C",
    category: "Network Security",
    difficulty: "Easy",
    active: true,
  },
  {
    questionText: "What is a 'honeypot' in cybersecurity?",
    optionA: "A type of ransomware",
    optionB: "A decoy system designed to lure and detect attackers",
    optionC: "A secure password manager",
    optionD: "A VPN protocol",
    correctOption: "B",
    category: "Network Security",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What is 'network segmentation' primarily used for?",
    optionA: "Increasing bandwidth",
    optionB: "Compressing network packets",
    optionC: "Isolating parts of a network to limit attack spread",
    optionD: "Monitoring employee internet activity",
    correctOption: "C",
    category: "Network Security",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "Which protocol provides secure remote login to network devices?",
    optionA: "Telnet",
    optionB: "SSH",
    optionC: "FTP",
    optionD: "HTTP",
    correctOption: "B",
    category: "Network Security",
    difficulty: "Easy",
    active: true,
  },

  // === MALWARE & THREATS ===
  {
    questionText: "What type of malware disguises itself as legitimate software to trick users into installing it?",
    optionA: "Worm",
    optionB: "Spyware",
    optionC: "Trojan Horse",
    optionD: "Adware",
    correctOption: "C",
    category: "Malware & Threats",
    difficulty: "Easy",
    active: true,
  },
  {
    questionText: "What distinguishes a 'worm' from a 'virus'?",
    optionA: "A worm requires user interaction to spread; a virus does not",
    optionB: "A worm self-replicates without attaching to host files; a virus does not",
    optionC: "A worm only affects mobile devices",
    optionD: "A worm encrypts files; a virus deletes them",
    correctOption: "B",
    category: "Malware & Threats",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What does 'ransomware' do to a victim's system?",
    optionA: "Steals login credentials silently",
    optionB: "Encrypts files and demands payment for decryption",
    optionC: "Sends spam emails to contacts",
    optionD: "Monitors keystrokes and screen activity",
    correctOption: "B",
    category: "Malware & Threats",
    difficulty: "Easy",
    active: true,
  },
  {
    questionText: "What is a 'rootkit'?",
    optionA: "A tool to recover deleted files",
    optionB: "Malware that gains root-level access and hides its presence on the system",
    optionC: "A type of phishing website",
    optionD: "A firewall bypass tool",
    correctOption: "B",
    category: "Malware & Threats",
    difficulty: "Hard",
    active: true,
  },
  {
    questionText: "Which of the following best describes a 'botnet'?",
    optionA: "A collection of compromised computers controlled by an attacker",
    optionB: "A network of security cameras",
    optionC: "An enterprise password vault",
    optionD: "A type of two-factor authentication",
    correctOption: "A",
    category: "Malware & Threats",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What is 'spyware' designed to do?",
    optionA: "Encrypt the victim's hard drive",
    optionB: "Display unwanted advertisements",
    optionC: "Secretly collect user data and activity without consent",
    optionD: "Block internet access",
    correctOption: "C",
    category: "Malware & Threats",
    difficulty: "Easy",
    active: true,
  },
  {
    questionText: "What is a 'zero-day exploit'?",
    optionA: "An attack that takes exactly 24 hours to execute",
    optionB: "An attack targeting a vulnerability before any patch or fix is available",
    optionC: "A malware that only activates on midnight",
    optionD: "A type of brute-force attack",
    correctOption: "B",
    category: "Malware & Threats",
    difficulty: "Hard",
    active: true,
  },
  {
    questionText: "Which action best protects against ransomware attacks?",
    optionA: "Using a longer password",
    optionB: "Maintaining regular offline backups of important data",
    optionC: "Disabling antivirus to improve performance",
    optionD: "Sharing credentials with IT staff only",
    correctOption: "B",
    category: "Malware & Threats",
    difficulty: "Medium",
    active: true,
  },

  // === WEB SECURITY ===
  {
    questionText: "What does 'XSS' stand for in web security?",
    optionA: "Extended Security Standard",
    optionB: "Cross-Site Scripting",
    optionC: "External Server Spoofing",
    optionD: "Extra Secure Socket",
    correctOption: "B",
    category: "Web Security",
    difficulty: "Easy",
    active: true,
  },
  {
    questionText: "In an SQL injection attack, what does the attacker inject into a query?",
    optionA: "Virus code",
    optionB: "Encrypted payloads",
    optionC: "Malicious SQL statements to manipulate the database",
    optionD: "False IP addresses",
    correctOption: "C",
    category: "Web Security",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What does CSRF stand for?",
    optionA: "Cyber Security Response Framework",
    optionB: "Cross-Site Request Forgery",
    optionC: "Centralized Secure Resource Filter",
    optionD: "Client-Side Request Format",
    correctOption: "B",
    category: "Web Security",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What HTTP security header helps prevent clickjacking attacks?",
    optionA: "Content-Security-Policy",
    optionB: "X-Frame-Options",
    optionC: "Strict-Transport-Security",
    optionD: "X-Content-Type-Options",
    correctOption: "B",
    category: "Web Security",
    difficulty: "Hard",
    active: true,
  },
  {
    questionText: "What does 'HTTPS' provide over standard 'HTTP'?",
    optionA: "Faster page load speeds",
    optionB: "Compressed data transfer",
    optionC: "Encrypted communication using TLS/SSL",
    optionD: "Automatic login functionality",
    correctOption: "C",
    category: "Web Security",
    difficulty: "Easy",
    active: true,
  },
  {
    questionText: "Which OWASP vulnerability involves using components with known security flaws?",
    optionA: "Broken Authentication",
    optionB: "Security Misconfiguration",
    optionC: "Using Components with Known Vulnerabilities",
    optionD: "Insecure Direct Object References",
    correctOption: "C",
    category: "Web Security",
    difficulty: "Hard",
    active: true,
  },
  {
    questionText: "What is 'directory traversal' in web security?",
    optionA: "Navigating between web pages without authentication",
    optionB: "An attack that accesses files outside the web root using path sequences like '../'",
    optionC: "A method for organizing website folders securely",
    optionD: "A technique to speed up file delivery",
    correctOption: "B",
    category: "Web Security",
    difficulty: "Hard",
    active: true,
  },
  {
    questionText: "What is the primary purpose of a Web Application Firewall (WAF)?",
    optionA: "To encrypt all web traffic",
    optionB: "To filter and monitor HTTP traffic and block common web attacks",
    optionC: "To speed up content delivery",
    optionD: "To manage SSL certificates",
    correctOption: "B",
    category: "Web Security",
    difficulty: "Medium",
    active: true,
  },

  // === AUTHENTICATION & ACCESS CONTROL ===
  {
    questionText: "What is multi-factor authentication (MFA)?",
    optionA: "Using multiple passwords for the same account",
    optionB: "Requiring verification from two or more independent categories of credentials",
    optionC: "Logging in from multiple devices simultaneously",
    optionD: "Using biometrics instead of passwords",
    correctOption: "B",
    category: "Authentication",
    difficulty: "Easy",
    active: true,
  },
  {
    questionText: "What is the 'principle of least privilege'?",
    optionA: "Giving users the maximum access needed for convenience",
    optionB: "Restricting user access rights to the minimum needed to perform their job",
    optionC: "Ensuring all users have the same access level",
    optionD: "Allowing administrators unlimited access",
    correctOption: "B",
    category: "Authentication",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What is a 'brute-force attack'?",
    optionA: "Physically damaging a server",
    optionB: "Tricking users into revealing their passwords",
    optionC: "Systematically trying all possible combinations to guess a password",
    optionD: "Intercepting encrypted traffic",
    correctOption: "C",
    category: "Authentication",
    difficulty: "Easy",
    active: true,
  },
  {
    questionText: "What is 'credential stuffing'?",
    optionA: "Storing passwords in plaintext",
    optionB: "Using leaked username/password pairs from one breach to try on other services",
    optionC: "Creating fake user accounts in bulk",
    optionD: "Encrypting credentials before storage",
    correctOption: "B",
    category: "Authentication",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "Which authentication factor is 'something you are'?",
    optionA: "Password",
    optionB: "Security token",
    optionC: "Biometrics like fingerprint or face scan",
    optionD: "PIN number",
    correctOption: "C",
    category: "Authentication",
    difficulty: "Easy",
    active: true,
  },
  {
    questionText: "What is a 'rainbow table attack'?",
    optionA: "A social engineering technique using colorful phishing emails",
    optionB: "Using precomputed hash values to crack password hashes quickly",
    optionC: "A brute force attack on Wi-Fi passwords",
    optionD: "An attack on rainbow-colored CAPTCHA systems",
    correctOption: "B",
    category: "Authentication",
    difficulty: "Hard",
    active: true,
  },
  {
    questionText: "What does SSO (Single Sign-On) allow a user to do?",
    optionA: "Reset passwords across multiple services simultaneously",
    optionB: "Sign in once and access multiple applications without re-authenticating",
    optionC: "Use one password for all accounts",
    optionD: "Login using only biometrics",
    correctOption: "B",
    category: "Authentication",
    difficulty: "Medium",
    active: true,
  },

  // === SOCIAL ENGINEERING ===
  {
    questionText: "What is 'spear phishing'?",
    optionA: "A broad phishing campaign targeting random users",
    optionB: "A highly targeted phishing attack aimed at a specific individual or organization",
    optionC: "Phishing attacks conducted via SMS",
    optionD: "Using AI-generated voices to trick victims",
    correctOption: "B",
    category: "Social Engineering",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What is 'vishing'?",
    optionA: "Visual phishing using fake images",
    optionB: "Phishing attacks conducted over voice calls",
    optionC: "Phishing attacks via video conferencing",
    optionD: "A type of malware delivered via USB",
    correctOption: "B",
    category: "Social Engineering",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What is 'pretexting' in social engineering?",
    optionA: "Sending automated spam emails",
    optionB: "Creating a fabricated scenario to manipulate someone into revealing information",
    optionC: "Using fake text messages",
    optionD: "Deploying malicious browser extensions",
    correctOption: "B",
    category: "Social Engineering",
    difficulty: "Hard",
    active: true,
  },
  {
    questionText: "What is 'tailgating' (or piggybacking) in physical security?",
    optionA: "Following someone too closely while driving",
    optionB: "Gaining unauthorized physical access by following an authorized person through a secure door",
    optionC: "Installing malware via a USB drive left behind",
    optionD: "Shoulder surfing to read passwords",
    correctOption: "B",
    category: "Social Engineering",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What is 'baiting' in the context of social engineering?",
    optionA: "Sending threatening emails to scare users",
    optionB: "Luring victims with something enticing (like a free USB drive) that contains malware",
    optionC: "Impersonating law enforcement",
    optionD: "Setting up fake Wi-Fi hotspots",
    correctOption: "B",
    category: "Social Engineering",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What is 'smishing'?",
    optionA: "Phishing attacks delivered via SMS/text messages",
    optionB: "Social media impersonation attacks",
    optionC: "Attacks targeting smart home devices",
    optionD: "Malware disguised as messaging apps",
    correctOption: "A",
    category: "Social Engineering",
    difficulty: "Easy",
    active: true,
  },

  // === CRYPTOGRAPHY ===
  {
    questionText: "What is the difference between symmetric and asymmetric encryption?",
    optionA: "Symmetric uses two keys; asymmetric uses one key",
    optionB: "Symmetric uses one shared key; asymmetric uses a public-private key pair",
    optionC: "Symmetric is more secure than asymmetric",
    optionD: "Symmetric encryption can only be used for small files",
    correctOption: "B",
    category: "Cryptography",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What is a 'digital certificate' used for?",
    optionA: "Backing up encryption keys",
    optionB: "Verifying the identity of a website or entity using a trusted CA",
    optionC: "Storing passwords securely",
    optionD: "Generating one-time passwords",
    correctOption: "B",
    category: "Cryptography",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What does 'hashing' do to data?",
    optionA: "Encrypts it so it can be decrypted later",
    optionB: "Converts it into a fixed-length string that cannot be reversed",
    optionC: "Compresses it for faster transmission",
    optionD: "Signs it with a digital signature",
    correctOption: "B",
    category: "Cryptography",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "Which hashing algorithm is currently considered most secure for password storage?",
    optionA: "MD5",
    optionB: "SHA-1",
    optionC: "bcrypt or Argon2",
    optionD: "Base64",
    correctOption: "C",
    category: "Cryptography",
    difficulty: "Hard",
    active: true,
  },
  {
    questionText: "What is 'end-to-end encryption' (E2EE)?",
    optionA: "Encrypting only the final destination server",
    optionB: "Encryption where only the communicating users can read the messages",
    optionC: "Encrypting only login credentials",
    optionD: "Encryption applied at the network layer only",
    correctOption: "B",
    category: "Cryptography",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What is a 'man-in-the-middle' (MITM) attack?",
    optionA: "An attack where a third party secretly intercepts and relays communication between two parties",
    optionB: "An attack where two hackers work together simultaneously",
    optionC: "An attack that targets the middleware layer of applications",
    optionD: "An attack targeting database administrators",
    correctOption: "A",
    category: "Cryptography",
    difficulty: "Medium",
    active: true,
  },

  // === INCIDENT RESPONSE & FORENSICS ===
  {
    questionText: "What is the first step in incident response?",
    optionA: "Eradication",
    optionB: "Containment",
    optionC: "Identification",
    optionD: "Recovery",
    correctOption: "C",
    category: "Incident Response",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What is 'digital forensics'?",
    optionA: "The practice of writing forensic reports about cyber crimes",
    optionB: "The process of collecting, preserving, and analyzing digital evidence from devices",
    optionC: "Creating digital signatures for evidence",
    optionD: "Securing digital crime scenes with firewalls",
    correctOption: "B",
    category: "Incident Response",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What does 'chain of custody' mean in digital forensics?",
    optionA: "The order in which security tools are deployed during an incident",
    optionB: "The documented process tracking who handled evidence and when",
    optionC: "A list of all compromised systems in a breach",
    optionD: "The escalation path in a security operations center",
    correctOption: "B",
    category: "Incident Response",
    difficulty: "Hard",
    active: true,
  },
  {
    questionText: "What is the purpose of a SIEM system?",
    optionA: "To manage employee passwords centrally",
    optionB: "To aggregate and analyze security event logs for threat detection",
    optionC: "To perform penetration testing automatically",
    optionD: "To encrypt data at rest",
    correctOption: "B",
    category: "Incident Response",
    difficulty: "Hard",
    active: true,
  },
  {
    questionText: "What is 'containment' in the incident response lifecycle?",
    optionA: "Documenting what happened during a breach",
    optionB: "Removing malware from infected systems",
    optionC: "Limiting the spread and impact of a security incident",
    optionD: "Notifying affected users about a breach",
    correctOption: "C",
    category: "Incident Response",
    difficulty: "Medium",
    active: true,
  },

  // === CLOUD & ENDPOINT SECURITY ===
  {
    questionText: "What is the 'shared responsibility model' in cloud security?",
    optionA: "Both the cloud provider and customer share the responsibility of securing cloud workloads",
    optionB: "The cloud provider is fully responsible for all security aspects",
    optionC: "The customer is fully responsible for everything in the cloud",
    optionD: "Security responsibility is shared equally between employees",
    correctOption: "A",
    category: "Cloud Security",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What is 'cloud misconfiguration' and why is it dangerous?",
    optionA: "An error in cloud software updates that causes outages",
    optionB: "Incorrectly set cloud permissions or settings that expose data publicly",
    optionC: "Using the wrong cloud provider for a business",
    optionD: "Running outdated operating systems in the cloud",
    correctOption: "B",
    category: "Cloud Security",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What is EDR (Endpoint Detection and Response)?",
    optionA: "A tool for encrypting endpoint hard drives",
    optionB: "Security software that monitors endpoints for threats and enables rapid response",
    optionC: "A type of VPN for mobile devices",
    optionD: "An email filtering solution",
    correctOption: "B",
    category: "Cloud Security",
    difficulty: "Hard",
    active: true,
  },
  {
    questionText: "What does 'CASB' stand for in cloud security?",
    optionA: "Cloud Access Security Broker",
    optionB: "Centralized Application Security Bridge",
    optionC: "Cyber Audit and Security Bureau",
    optionD: "Cloud Application Service Barrier",
    correctOption: "A",
    category: "Cloud Security",
    difficulty: "Hard",
    active: true,
  },

  // === GENERAL SECURITY ===
  {
    questionText: "What is 'security through obscurity'?",
    optionA: "Using complex encryption algorithms",
    optionB: "Relying on secrecy of design or implementation to provide security, which is considered weak",
    optionC: "Hiding servers behind multiple firewalls",
    optionD: "Using anonymous browsing tools",
    correctOption: "B",
    category: "General Security",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What is a 'CVE' number?",
    optionA: "A unique identifier for a publicly known cybersecurity vulnerability",
    optionB: "A security certification for professionals",
    optionC: "A type of encryption protocol",
    optionD: "A code for categorizing viruses",
    correctOption: "A",
    category: "General Security",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What is 'patch management'?",
    optionA: "Managing network infrastructure upgrades",
    optionB: "The process of applying updates to fix security vulnerabilities in software",
    optionC: "Creating backup copies of software",
    optionD: "Testing new software before deployment",
    correctOption: "B",
    category: "General Security",
    difficulty: "Easy",
    active: true,
  },
  {
    questionText: "What is a 'penetration test' (pen test)?",
    optionA: "A test to check internet connection speeds",
    optionB: "An authorized simulated attack to evaluate security weaknesses",
    optionC: "A tool to measure firewall efficiency",
    optionD: "A stress test on server hardware",
    correctOption: "B",
    category: "General Security",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What does 'GDPR' primarily protect?",
    optionA: "Government classified information",
    optionB: "Personal data and privacy of individuals in the European Union",
    optionC: "Intellectual property of corporations",
    optionD: "Financial transactions in Europe",
    correctOption: "B",
    category: "General Security",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What is a 'security audit'?",
    optionA: "Monitoring user behavior on the internet",
    optionB: "A systematic evaluation of an organization's security posture and controls",
    optionC: "Testing the performance of security hardware",
    optionD: "Reviewing antivirus software logs",
    correctOption: "B",
    category: "General Security",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What does 'data exfiltration' mean?",
    optionA: "Filtering spam data from email",
    optionB: "Unauthorized transfer of data from an organization to an external location",
    optionC: "Backing up data to a cloud server",
    optionD: "Encrypting data for secure transmission",
    correctOption: "B",
    category: "General Security",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What is 'defense in depth'?",
    optionA: "A single powerful firewall to block all attacks",
    optionB: "A layered security strategy using multiple controls to protect assets",
    optionC: "Encrypting all data at maximum strength",
    optionD: "Hiring more security staff",
    correctOption: "B",
    category: "General Security",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What is a 'security information sharing' program?",
    optionA: "Sharing employee passwords for convenience",
    optionB: "Sharing threat intelligence and attack data between organizations to improve collective defense",
    optionC: "Publishing security audit results publicly",
    optionD: "Sharing server access logs with regulators",
    correctOption: "B",
    category: "General Security",
    difficulty: "Hard",
    active: true,
  },
  {
    questionText: "What does 'non-repudiation' mean in information security?",
    optionA: "Ensuring data cannot be accessed without authorization",
    optionB: "Guaranteeing that a sender cannot deny having sent a message",
    optionC: "Preventing unauthorized modifications to data",
    optionD: "Encrypting messages to prevent eavesdropping",
    correctOption: "B",
    category: "Cryptography",
    difficulty: "Hard",
    active: true,
  },
  {
    questionText: "What is 'threat modeling'?",
    optionA: "Creating 3D models of cyberattack scenarios",
    optionB: "A structured approach to identifying, prioritizing, and mitigating potential security threats",
    optionC: "Modeling network topologies to find weak points",
    optionD: "Predicting future malware trends using AI",
    correctOption: "B",
    category: "General Security",
    difficulty: "Hard",
    active: true,
  },
  {
    questionText: "What is a 'supply chain attack'?",
    optionA: "Attacking a company's logistics and shipping systems",
    optionB: "Compromising a trusted software vendor or supplier to reach the target's systems",
    optionC: "A distributed denial-of-service attack on retail websites",
    optionD: "Stealing goods during transit using cyber means",
    correctOption: "B",
    category: "General Security",
    difficulty: "Hard",
    active: true,
  },
  {
    questionText: "What is the purpose of a 'bug bounty' program?",
    optionA: "Rewarding employees who fix the most software bugs",
    optionB: "Offering rewards to ethical hackers for responsibly disclosing security vulnerabilities",
    optionC: "Paying vendors to patch vulnerabilities quickly",
    optionD: "Incentivizing developers to write bug-free code",
    correctOption: "B",
    category: "General Security",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What is 'lateral movement' in a cyberattack?",
    optionA: "An attacker moving between floors of a physical office",
    optionB: "Techniques used by attackers to progressively move deeper into a network after initial compromise",
    optionC: "Moving malware between different file types",
    optionD: "Switching between multiple C2 servers during an attack",
    correctOption: "B",
    category: "General Security",
    difficulty: "Hard",
    active: true,
  },
  {
    questionText: "What is 'OSINT' in cybersecurity?",
    optionA: "Open Source Intelligence – gathering information from publicly available sources",
    optionB: "Operating System Intrusion Testing",
    optionC: "A type of open-source antivirus tool",
    optionD: "Online Security and Intelligence Training",
    correctOption: "A",
    category: "General Security",
    difficulty: "Medium",
    active: true,
  },
  {
    questionText: "What is 'data masking'?",
    optionA: "Hiding the location of servers",
    optionB: "Replacing sensitive data with fictitious but realistic values to protect it in non-production environments",
    optionC: "Encrypting backup files",
    optionD: "Anonymizing user IP addresses",
    correctOption: "B",
    category: "General Security",
    difficulty: "Hard",
    active: true,
  },
];

async function main() {
  console.log(`Adding ${questions.length} new cybersecurity questions...`);
  let count = 0;
  for (const q of questions) {
    try {
      await prisma.question.create({ data: q });
      count++;
    } catch (e) {
      // skip duplicates silently
    }
  }
  console.log(`✅ Successfully added ${count} questions!`);

  const total = await prisma.question.count();
  const active = await prisma.question.count({ where: { active: true } });
  console.log(`📊 Total questions in DB: ${total} (${active} active)`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
